/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as EcoHubRouteRouteImport } from './routes/eco-hub/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as EcoHubIndexRouteImport } from './routes/eco-hub/index'
import { Route as MarketplaceItemIdRouteImport } from './routes/marketplace/$itemId'
import { Route as UnauthenticatedRegisterRouteImport } from './routes/_unauthenticated/register'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as ProfileUserIdRouteRouteImport } from './routes/profile/$userId/route'
import { Route as EcoHubQuizzesRouteRouteImport } from './routes/eco-hub/quizzes/route'
import { Route as EcoHubBlogsRouteRouteImport } from './routes/eco-hub/blogs/route'
import { Route as AuthenticatedReviewsRouteRouteImport } from './routes/_authenticated/reviews/route'
import { Route as AuthenticatedWriterRouteRouteImport } from './routes/_authenticated/_writer/route'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as EcoHubQuizzesIndexRouteImport } from './routes/eco-hub/quizzes/index'
import { Route as EcoHubBlogsIndexRouteImport } from './routes/eco-hub/blogs/index'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews/index'
import { Route as AuthenticatedOffersIndexRouteImport } from './routes/_authenticated/offers/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ProfileUserIdReviewsRouteImport } from './routes/profile/$userId/reviews'
import { Route as ProfileUserIdItemsRouteImport } from './routes/profile/$userId/items'
import { Route as EcoHubBlogsBlogsIdRouteImport } from './routes/eco-hub/blogs/$blogsId'
import { Route as AuthenticatedOffersReceivedRouteImport } from './routes/_authenticated/offers/received'
import { Route as AuthenticatedOffersOwnRouteImport } from './routes/_authenticated/offers/own'
import { Route as AuthenticatedNotificationsNotificationIdRouteImport } from './routes/_authenticated/notifications/$notificationId'
import { Route as AuthenticatedMarketplaceWishlistRouteImport } from './routes/_authenticated/marketplace/wishlist'
import { Route as AuthenticatedMarketplaceMyItemsRouteImport } from './routes/_authenticated/marketplace/my-items'
import { Route as AuthenticatedMarketplaceHistoryRouteImport } from './routes/_authenticated/marketplace/history'
import { Route as AuthenticatedMarketplaceCreateRouteImport } from './routes/_authenticated/marketplace/create'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedReviewsLayoutRouteRouteImport } from './routes/_authenticated/reviews/_layout/route'
import { Route as AuthenticatedWriterEcoHubRouteRouteImport } from './routes/_authenticated/_writer/eco-hub/route'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin/categories/index'
import { Route as AuthenticatedReviewsCreateOfferIdRouteImport } from './routes/_authenticated/reviews/create/$offerId'
import { Route as AuthenticatedReviewsLayoutReceivedRouteImport } from './routes/_authenticated/reviews/_layout/received'
import { Route as AuthenticatedReviewsLayoutGivenRouteImport } from './routes/_authenticated/reviews/_layout/given'
import { Route as AuthenticatedMarketplaceItemIdEditRouteImport } from './routes/_authenticated/marketplace/$itemId.edit'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users/$userId'
import { Route as AuthenticatedAdminUsersUserIdIndexRouteImport } from './routes/_authenticated/admin/users/$userId/index'
import { Route as AuthenticatedAdminUsersUserIdItemsRouteImport } from './routes/_authenticated/admin/users/$userId/items'
import { Route as AuthenticatedWriterEcoHubQuizzesOwnRouteImport } from './routes/_authenticated/_writer/eco-hub/quizzes/own'
import { Route as AuthenticatedWriterEcoHubBlogsOwnRouteImport } from './routes/_authenticated/_writer/eco-hub/blogs/own'
import { Route as AuthenticatedWriterEcoHubBlogsCreateRouteImport } from './routes/_authenticated/_writer/eco-hub/blogs/create'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoHubRouteRoute = EcoHubRouteRouteImport.update({
  id: '/eco-hub',
  path: '/eco-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const EcoHubIndexRoute = EcoHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcoHubRouteRoute,
} as any)
const MarketplaceItemIdRoute = MarketplaceItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const UnauthenticatedRegisterRoute = UnauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ProfileUserIdRouteRoute = ProfileUserIdRouteRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoHubQuizzesRouteRoute = EcoHubQuizzesRouteRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => EcoHubRouteRoute,
} as any)
const EcoHubBlogsRouteRoute = EcoHubBlogsRouteRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => EcoHubRouteRoute,
} as any)
const AuthenticatedReviewsRouteRoute =
  AuthenticatedReviewsRouteRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWriterRouteRoute =
  AuthenticatedWriterRouteRouteImport.update({
    id: '/_writer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUserIdRouteRoute,
} as any)
const EcoHubQuizzesIndexRoute = EcoHubQuizzesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcoHubQuizzesRouteRoute,
} as any)
const EcoHubBlogsIndexRoute = EcoHubBlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcoHubBlogsRouteRoute,
} as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReviewsRouteRoute,
  } as any)
const AuthenticatedOffersIndexRoute =
  AuthenticatedOffersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOffersRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ProfileUserIdReviewsRoute = ProfileUserIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProfileUserIdRouteRoute,
} as any)
const ProfileUserIdItemsRoute = ProfileUserIdItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => ProfileUserIdRouteRoute,
} as any)
const EcoHubBlogsBlogsIdRoute = EcoHubBlogsBlogsIdRouteImport.update({
  id: '/$blogsId',
  path: '/$blogsId',
  getParentRoute: () => EcoHubBlogsRouteRoute,
} as any)
const AuthenticatedOffersReceivedRoute =
  AuthenticatedOffersReceivedRouteImport.update({
    id: '/received',
    path: '/received',
    getParentRoute: () => AuthenticatedOffersRoute,
  } as any)
const AuthenticatedOffersOwnRoute = AuthenticatedOffersOwnRouteImport.update({
  id: '/own',
  path: '/own',
  getParentRoute: () => AuthenticatedOffersRoute,
} as any)
const AuthenticatedNotificationsNotificationIdRoute =
  AuthenticatedNotificationsNotificationIdRouteImport.update({
    id: '/notifications/$notificationId',
    path: '/notifications/$notificationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketplaceWishlistRoute =
  AuthenticatedMarketplaceWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceMyItemsRoute =
  AuthenticatedMarketplaceMyItemsRouteImport.update({
    id: '/my-items',
    path: '/my-items',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceHistoryRoute =
  AuthenticatedMarketplaceHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceCreateRoute =
  AuthenticatedMarketplaceCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedReviewsLayoutRouteRoute =
  AuthenticatedReviewsLayoutRouteRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedReviewsRouteRoute,
  } as any)
const AuthenticatedWriterEcoHubRouteRoute =
  AuthenticatedWriterEcoHubRouteRouteImport.update({
    id: '/eco-hub',
    path: '/eco-hub',
    getParentRoute: () => AuthenticatedWriterRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedReviewsCreateOfferIdRoute =
  AuthenticatedReviewsCreateOfferIdRouteImport.update({
    id: '/create/$offerId',
    path: '/create/$offerId',
    getParentRoute: () => AuthenticatedReviewsRouteRoute,
  } as any)
const AuthenticatedReviewsLayoutReceivedRoute =
  AuthenticatedReviewsLayoutReceivedRouteImport.update({
    id: '/received',
    path: '/received',
    getParentRoute: () => AuthenticatedReviewsLayoutRouteRoute,
  } as any)
const AuthenticatedReviewsLayoutGivenRoute =
  AuthenticatedReviewsLayoutGivenRouteImport.update({
    id: '/given',
    path: '/given',
    getParentRoute: () => AuthenticatedReviewsLayoutRouteRoute,
  } as any)
const AuthenticatedMarketplaceItemIdEditRoute =
  AuthenticatedMarketplaceItemIdEditRouteImport.update({
    id: '/$itemId/edit',
    path: '/$itemId/edit',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminUsersUserIdIndexRoute =
  AuthenticatedAdminUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)
const AuthenticatedAdminUsersUserIdItemsRoute =
  AuthenticatedAdminUsersUserIdItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => AuthenticatedAdminUsersUserIdRoute,
  } as any)
const AuthenticatedWriterEcoHubQuizzesOwnRoute =
  AuthenticatedWriterEcoHubQuizzesOwnRouteImport.update({
    id: '/quizzes/own',
    path: '/quizzes/own',
    getParentRoute: () => AuthenticatedWriterEcoHubRouteRoute,
  } as any)
const AuthenticatedWriterEcoHubBlogsOwnRoute =
  AuthenticatedWriterEcoHubBlogsOwnRouteImport.update({
    id: '/blogs/own',
    path: '/blogs/own',
    getParentRoute: () => AuthenticatedWriterEcoHubRouteRoute,
  } as any)
const AuthenticatedWriterEcoHubBlogsCreateRoute =
  AuthenticatedWriterEcoHubBlogsCreateRouteImport.update({
    id: '/blogs/create',
    path: '/blogs/create',
    getParentRoute: () => AuthenticatedWriterEcoHubRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eco-hub': typeof AuthenticatedWriterEcoHubRouteRouteWithChildren
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/reviews': typeof AuthenticatedReviewsLayoutRouteRouteWithChildren
  '/eco-hub/blogs': typeof EcoHubBlogsRouteRouteWithChildren
  '/eco-hub/quizzes': typeof EcoHubQuizzesRouteRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRouteRouteWithChildren
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/marketplace/$itemId': typeof MarketplaceItemIdRoute
  '/eco-hub/': typeof EcoHubIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/marketplace/create': typeof AuthenticatedMarketplaceCreateRoute
  '/marketplace/history': typeof AuthenticatedMarketplaceHistoryRoute
  '/marketplace/my-items': typeof AuthenticatedMarketplaceMyItemsRoute
  '/marketplace/wishlist': typeof AuthenticatedMarketplaceWishlistRoute
  '/notifications/$notificationId': typeof AuthenticatedNotificationsNotificationIdRoute
  '/offers/own': typeof AuthenticatedOffersOwnRoute
  '/offers/received': typeof AuthenticatedOffersReceivedRoute
  '/eco-hub/blogs/$blogsId': typeof EcoHubBlogsBlogsIdRoute
  '/profile/$userId/items': typeof ProfileUserIdItemsRoute
  '/profile/$userId/reviews': typeof ProfileUserIdReviewsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/offers/': typeof AuthenticatedOffersIndexRoute
  '/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/eco-hub/blogs/': typeof EcoHubBlogsIndexRoute
  '/eco-hub/quizzes/': typeof EcoHubQuizzesIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/marketplace/$itemId/edit': typeof AuthenticatedMarketplaceItemIdEditRoute
  '/reviews/given': typeof AuthenticatedReviewsLayoutGivenRoute
  '/reviews/received': typeof AuthenticatedReviewsLayoutReceivedRoute
  '/reviews/create/$offerId': typeof AuthenticatedReviewsCreateOfferIdRoute
  '/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/eco-hub/blogs/create': typeof AuthenticatedWriterEcoHubBlogsCreateRoute
  '/eco-hub/blogs/own': typeof AuthenticatedWriterEcoHubBlogsOwnRoute
  '/eco-hub/quizzes/own': typeof AuthenticatedWriterEcoHubQuizzesOwnRoute
  '/admin/users/$userId/items': typeof AuthenticatedAdminUsersUserIdItemsRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/about': typeof AuthenticatedAboutRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/marketplace/$itemId': typeof MarketplaceItemIdRoute
  '/eco-hub': typeof AuthenticatedWriterEcoHubRouteRouteWithChildren
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/marketplace/create': typeof AuthenticatedMarketplaceCreateRoute
  '/marketplace/history': typeof AuthenticatedMarketplaceHistoryRoute
  '/marketplace/my-items': typeof AuthenticatedMarketplaceMyItemsRoute
  '/marketplace/wishlist': typeof AuthenticatedMarketplaceWishlistRoute
  '/notifications/$notificationId': typeof AuthenticatedNotificationsNotificationIdRoute
  '/offers/own': typeof AuthenticatedOffersOwnRoute
  '/offers/received': typeof AuthenticatedOffersReceivedRoute
  '/eco-hub/blogs/$blogsId': typeof EcoHubBlogsBlogsIdRoute
  '/profile/$userId/items': typeof ProfileUserIdItemsRoute
  '/profile/$userId/reviews': typeof ProfileUserIdReviewsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/offers': typeof AuthenticatedOffersIndexRoute
  '/eco-hub/blogs': typeof EcoHubBlogsIndexRoute
  '/eco-hub/quizzes': typeof EcoHubQuizzesIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/marketplace/$itemId/edit': typeof AuthenticatedMarketplaceItemIdEditRoute
  '/reviews/given': typeof AuthenticatedReviewsLayoutGivenRoute
  '/reviews/received': typeof AuthenticatedReviewsLayoutReceivedRoute
  '/reviews/create/$offerId': typeof AuthenticatedReviewsCreateOfferIdRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/eco-hub/blogs/create': typeof AuthenticatedWriterEcoHubBlogsCreateRoute
  '/eco-hub/blogs/own': typeof AuthenticatedWriterEcoHubBlogsOwnRoute
  '/eco-hub/quizzes/own': typeof AuthenticatedWriterEcoHubQuizzesOwnRoute
  '/admin/users/$userId/items': typeof AuthenticatedAdminUsersUserIdItemsRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eco-hub': typeof EcoHubRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/_writer': typeof AuthenticatedWriterRouteRouteWithChildren
  '/_authenticated/reviews': typeof AuthenticatedReviewsRouteRouteWithChildren
  '/eco-hub/blogs': typeof EcoHubBlogsRouteRouteWithChildren
  '/eco-hub/quizzes': typeof EcoHubQuizzesRouteRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRouteRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/offers': typeof AuthenticatedOffersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_unauthenticated/register': typeof UnauthenticatedRegisterRoute
  '/marketplace/$itemId': typeof MarketplaceItemIdRoute
  '/eco-hub/': typeof EcoHubIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/_writer/eco-hub': typeof AuthenticatedWriterEcoHubRouteRouteWithChildren
  '/_authenticated/reviews/_layout': typeof AuthenticatedReviewsLayoutRouteRouteWithChildren
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/marketplace/create': typeof AuthenticatedMarketplaceCreateRoute
  '/_authenticated/marketplace/history': typeof AuthenticatedMarketplaceHistoryRoute
  '/_authenticated/marketplace/my-items': typeof AuthenticatedMarketplaceMyItemsRoute
  '/_authenticated/marketplace/wishlist': typeof AuthenticatedMarketplaceWishlistRoute
  '/_authenticated/notifications/$notificationId': typeof AuthenticatedNotificationsNotificationIdRoute
  '/_authenticated/offers/own': typeof AuthenticatedOffersOwnRoute
  '/_authenticated/offers/received': typeof AuthenticatedOffersReceivedRoute
  '/eco-hub/blogs/$blogsId': typeof EcoHubBlogsBlogsIdRoute
  '/profile/$userId/items': typeof ProfileUserIdItemsRoute
  '/profile/$userId/reviews': typeof ProfileUserIdReviewsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/offers/': typeof AuthenticatedOffersIndexRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/eco-hub/blogs/': typeof EcoHubBlogsIndexRoute
  '/eco-hub/quizzes/': typeof EcoHubQuizzesIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  '/_authenticated/marketplace/$itemId/edit': typeof AuthenticatedMarketplaceItemIdEditRoute
  '/_authenticated/reviews/_layout/given': typeof AuthenticatedReviewsLayoutGivenRoute
  '/_authenticated/reviews/_layout/received': typeof AuthenticatedReviewsLayoutReceivedRoute
  '/_authenticated/reviews/create/$offerId': typeof AuthenticatedReviewsCreateOfferIdRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/_writer/eco-hub/blogs/create': typeof AuthenticatedWriterEcoHubBlogsCreateRoute
  '/_authenticated/_writer/eco-hub/blogs/own': typeof AuthenticatedWriterEcoHubBlogsOwnRoute
  '/_authenticated/_writer/eco-hub/quizzes/own': typeof AuthenticatedWriterEcoHubQuizzesOwnRoute
  '/_authenticated/admin/users/$userId/items': typeof AuthenticatedAdminUsersUserIdItemsRoute
  '/_authenticated/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eco-hub'
    | '/marketplace'
    | '/unauthorized'
    | '/reviews'
    | '/eco-hub/blogs'
    | '/eco-hub/quizzes'
    | '/profile/$userId'
    | '/about'
    | '/admin'
    | '/offers'
    | '/profile'
    | '/login'
    | '/register'
    | '/marketplace/$itemId'
    | '/eco-hub/'
    | '/marketplace/'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/marketplace/create'
    | '/marketplace/history'
    | '/marketplace/my-items'
    | '/marketplace/wishlist'
    | '/notifications/$notificationId'
    | '/offers/own'
    | '/offers/received'
    | '/eco-hub/blogs/$blogsId'
    | '/profile/$userId/items'
    | '/profile/$userId/reviews'
    | '/admin/'
    | '/notifications/'
    | '/offers/'
    | '/reviews/'
    | '/eco-hub/blogs/'
    | '/eco-hub/quizzes/'
    | '/profile/$userId/'
    | '/admin/users/$userId'
    | '/marketplace/$itemId/edit'
    | '/reviews/given'
    | '/reviews/received'
    | '/reviews/create/$offerId'
    | '/admin/categories/'
    | '/admin/users/'
    | '/eco-hub/blogs/create'
    | '/eco-hub/blogs/own'
    | '/eco-hub/quizzes/own'
    | '/admin/users/$userId/items'
    | '/admin/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/about'
    | '/marketplace'
    | '/profile'
    | '/login'
    | '/register'
    | '/marketplace/$itemId'
    | '/eco-hub'
    | '/reviews'
    | '/admin/dashboard'
    | '/marketplace/create'
    | '/marketplace/history'
    | '/marketplace/my-items'
    | '/marketplace/wishlist'
    | '/notifications/$notificationId'
    | '/offers/own'
    | '/offers/received'
    | '/eco-hub/blogs/$blogsId'
    | '/profile/$userId/items'
    | '/profile/$userId/reviews'
    | '/admin'
    | '/notifications'
    | '/offers'
    | '/eco-hub/blogs'
    | '/eco-hub/quizzes'
    | '/profile/$userId'
    | '/marketplace/$itemId/edit'
    | '/reviews/given'
    | '/reviews/received'
    | '/reviews/create/$offerId'
    | '/admin/categories'
    | '/admin/users'
    | '/eco-hub/blogs/create'
    | '/eco-hub/blogs/own'
    | '/eco-hub/quizzes/own'
    | '/admin/users/$userId/items'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/eco-hub'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/marketplace'
    | '/unauthorized'
    | '/_authenticated/_writer'
    | '/_authenticated/reviews'
    | '/eco-hub/blogs'
    | '/eco-hub/quizzes'
    | '/profile/$userId'
    | '/_authenticated/about'
    | '/_authenticated/admin'
    | '/_authenticated/marketplace'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/_unauthenticated/login'
    | '/_unauthenticated/register'
    | '/marketplace/$itemId'
    | '/eco-hub/'
    | '/marketplace/'
    | '/_authenticated/_writer/eco-hub'
    | '/_authenticated/reviews/_layout'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/users'
    | '/_authenticated/marketplace/create'
    | '/_authenticated/marketplace/history'
    | '/_authenticated/marketplace/my-items'
    | '/_authenticated/marketplace/wishlist'
    | '/_authenticated/notifications/$notificationId'
    | '/_authenticated/offers/own'
    | '/_authenticated/offers/received'
    | '/eco-hub/blogs/$blogsId'
    | '/profile/$userId/items'
    | '/profile/$userId/reviews'
    | '/_authenticated/admin/'
    | '/_authenticated/notifications/'
    | '/_authenticated/offers/'
    | '/_authenticated/reviews/'
    | '/eco-hub/blogs/'
    | '/eco-hub/quizzes/'
    | '/profile/$userId/'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/marketplace/$itemId/edit'
    | '/_authenticated/reviews/_layout/given'
    | '/_authenticated/reviews/_layout/received'
    | '/_authenticated/reviews/create/$offerId'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/_writer/eco-hub/blogs/create'
    | '/_authenticated/_writer/eco-hub/blogs/own'
    | '/_authenticated/_writer/eco-hub/quizzes/own'
    | '/_authenticated/admin/users/$userId/items'
    | '/_authenticated/admin/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcoHubRouteRoute: typeof EcoHubRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  ProfileUserIdRouteRoute: typeof ProfileUserIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco-hub': {
      id: '/eco-hub'
      path: '/eco-hub'
      fullPath: '/eco-hub'
      preLoaderRoute: typeof EcoHubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/eco-hub/': {
      id: '/eco-hub/'
      path: '/'
      fullPath: '/eco-hub/'
      preLoaderRoute: typeof EcoHubIndexRouteImport
      parentRoute: typeof EcoHubRouteRoute
    }
    '/marketplace/$itemId': {
      id: '/marketplace/$itemId'
      path: '/$itemId'
      fullPath: '/marketplace/$itemId'
      preLoaderRoute: typeof MarketplaceItemIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/_unauthenticated/register': {
      id: '/_unauthenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthenticatedRegisterRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco-hub/quizzes': {
      id: '/eco-hub/quizzes'
      path: '/quizzes'
      fullPath: '/eco-hub/quizzes'
      preLoaderRoute: typeof EcoHubQuizzesRouteRouteImport
      parentRoute: typeof EcoHubRouteRoute
    }
    '/eco-hub/blogs': {
      id: '/eco-hub/blogs'
      path: '/blogs'
      fullPath: '/eco-hub/blogs'
      preLoaderRoute: typeof EcoHubBlogsRouteRouteImport
      parentRoute: typeof EcoHubRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_writer': {
      id: '/_authenticated/_writer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWriterRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof ProfileUserIdRouteRoute
    }
    '/eco-hub/quizzes/': {
      id: '/eco-hub/quizzes/'
      path: '/'
      fullPath: '/eco-hub/quizzes/'
      preLoaderRoute: typeof EcoHubQuizzesIndexRouteImport
      parentRoute: typeof EcoHubQuizzesRouteRoute
    }
    '/eco-hub/blogs/': {
      id: '/eco-hub/blogs/'
      path: '/'
      fullPath: '/eco-hub/blogs/'
      preLoaderRoute: typeof EcoHubBlogsIndexRouteImport
      parentRoute: typeof EcoHubBlogsRouteRoute
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedReviewsRouteRoute
    }
    '/_authenticated/offers/': {
      id: '/_authenticated/offers/'
      path: '/'
      fullPath: '/offers/'
      preLoaderRoute: typeof AuthenticatedOffersIndexRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/profile/$userId/reviews': {
      id: '/profile/$userId/reviews'
      path: '/reviews'
      fullPath: '/profile/$userId/reviews'
      preLoaderRoute: typeof ProfileUserIdReviewsRouteImport
      parentRoute: typeof ProfileUserIdRouteRoute
    }
    '/profile/$userId/items': {
      id: '/profile/$userId/items'
      path: '/items'
      fullPath: '/profile/$userId/items'
      preLoaderRoute: typeof ProfileUserIdItemsRouteImport
      parentRoute: typeof ProfileUserIdRouteRoute
    }
    '/eco-hub/blogs/$blogsId': {
      id: '/eco-hub/blogs/$blogsId'
      path: '/$blogsId'
      fullPath: '/eco-hub/blogs/$blogsId'
      preLoaderRoute: typeof EcoHubBlogsBlogsIdRouteImport
      parentRoute: typeof EcoHubBlogsRouteRoute
    }
    '/_authenticated/offers/received': {
      id: '/_authenticated/offers/received'
      path: '/received'
      fullPath: '/offers/received'
      preLoaderRoute: typeof AuthenticatedOffersReceivedRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/offers/own': {
      id: '/_authenticated/offers/own'
      path: '/own'
      fullPath: '/offers/own'
      preLoaderRoute: typeof AuthenticatedOffersOwnRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/notifications/$notificationId': {
      id: '/_authenticated/notifications/$notificationId'
      path: '/notifications/$notificationId'
      fullPath: '/notifications/$notificationId'
      preLoaderRoute: typeof AuthenticatedNotificationsNotificationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace/wishlist': {
      id: '/_authenticated/marketplace/wishlist'
      path: '/wishlist'
      fullPath: '/marketplace/wishlist'
      preLoaderRoute: typeof AuthenticatedMarketplaceWishlistRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/my-items': {
      id: '/_authenticated/marketplace/my-items'
      path: '/my-items'
      fullPath: '/marketplace/my-items'
      preLoaderRoute: typeof AuthenticatedMarketplaceMyItemsRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/history': {
      id: '/_authenticated/marketplace/history'
      path: '/history'
      fullPath: '/marketplace/history'
      preLoaderRoute: typeof AuthenticatedMarketplaceHistoryRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/create': {
      id: '/_authenticated/marketplace/create'
      path: '/create'
      fullPath: '/marketplace/create'
      preLoaderRoute: typeof AuthenticatedMarketplaceCreateRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/reviews/_layout': {
      id: '/_authenticated/reviews/_layout'
      path: ''
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsLayoutRouteRouteImport
      parentRoute: typeof AuthenticatedReviewsRouteRoute
    }
    '/_authenticated/_writer/eco-hub': {
      id: '/_authenticated/_writer/eco-hub'
      path: '/eco-hub'
      fullPath: '/eco-hub'
      preLoaderRoute: typeof AuthenticatedWriterEcoHubRouteRouteImport
      parentRoute: typeof AuthenticatedWriterRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/reviews/create/$offerId': {
      id: '/_authenticated/reviews/create/$offerId'
      path: '/create/$offerId'
      fullPath: '/reviews/create/$offerId'
      preLoaderRoute: typeof AuthenticatedReviewsCreateOfferIdRouteImport
      parentRoute: typeof AuthenticatedReviewsRouteRoute
    }
    '/_authenticated/reviews/_layout/received': {
      id: '/_authenticated/reviews/_layout/received'
      path: '/received'
      fullPath: '/reviews/received'
      preLoaderRoute: typeof AuthenticatedReviewsLayoutReceivedRouteImport
      parentRoute: typeof AuthenticatedReviewsLayoutRouteRoute
    }
    '/_authenticated/reviews/_layout/given': {
      id: '/_authenticated/reviews/_layout/given'
      path: '/given'
      fullPath: '/reviews/given'
      preLoaderRoute: typeof AuthenticatedReviewsLayoutGivenRouteImport
      parentRoute: typeof AuthenticatedReviewsLayoutRouteRoute
    }
    '/_authenticated/marketplace/$itemId/edit': {
      id: '/_authenticated/marketplace/$itemId/edit'
      path: '/$itemId/edit'
      fullPath: '/marketplace/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedMarketplaceItemIdEditRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/users/$userId/': {
      id: '/_authenticated/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
    '/_authenticated/admin/users/$userId/items': {
      id: '/_authenticated/admin/users/$userId/items'
      path: '/items'
      fullPath: '/admin/users/$userId/items'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdItemsRouteImport
      parentRoute: typeof AuthenticatedAdminUsersUserIdRoute
    }
    '/_authenticated/_writer/eco-hub/quizzes/own': {
      id: '/_authenticated/_writer/eco-hub/quizzes/own'
      path: '/quizzes/own'
      fullPath: '/eco-hub/quizzes/own'
      preLoaderRoute: typeof AuthenticatedWriterEcoHubQuizzesOwnRouteImport
      parentRoute: typeof AuthenticatedWriterEcoHubRouteRoute
    }
    '/_authenticated/_writer/eco-hub/blogs/own': {
      id: '/_authenticated/_writer/eco-hub/blogs/own'
      path: '/blogs/own'
      fullPath: '/eco-hub/blogs/own'
      preLoaderRoute: typeof AuthenticatedWriterEcoHubBlogsOwnRouteImport
      parentRoute: typeof AuthenticatedWriterEcoHubRouteRoute
    }
    '/_authenticated/_writer/eco-hub/blogs/create': {
      id: '/_authenticated/_writer/eco-hub/blogs/create'
      path: '/blogs/create'
      fullPath: '/eco-hub/blogs/create'
      preLoaderRoute: typeof AuthenticatedWriterEcoHubBlogsCreateRouteImport
      parentRoute: typeof AuthenticatedWriterEcoHubRouteRoute
    }
  }
}

interface EcoHubBlogsRouteRouteChildren {
  EcoHubBlogsBlogsIdRoute: typeof EcoHubBlogsBlogsIdRoute
  EcoHubBlogsIndexRoute: typeof EcoHubBlogsIndexRoute
}

const EcoHubBlogsRouteRouteChildren: EcoHubBlogsRouteRouteChildren = {
  EcoHubBlogsBlogsIdRoute: EcoHubBlogsBlogsIdRoute,
  EcoHubBlogsIndexRoute: EcoHubBlogsIndexRoute,
}

const EcoHubBlogsRouteRouteWithChildren =
  EcoHubBlogsRouteRoute._addFileChildren(EcoHubBlogsRouteRouteChildren)

interface EcoHubQuizzesRouteRouteChildren {
  EcoHubQuizzesIndexRoute: typeof EcoHubQuizzesIndexRoute
}

const EcoHubQuizzesRouteRouteChildren: EcoHubQuizzesRouteRouteChildren = {
  EcoHubQuizzesIndexRoute: EcoHubQuizzesIndexRoute,
}

const EcoHubQuizzesRouteRouteWithChildren =
  EcoHubQuizzesRouteRoute._addFileChildren(EcoHubQuizzesRouteRouteChildren)

interface EcoHubRouteRouteChildren {
  EcoHubBlogsRouteRoute: typeof EcoHubBlogsRouteRouteWithChildren
  EcoHubQuizzesRouteRoute: typeof EcoHubQuizzesRouteRouteWithChildren
  EcoHubIndexRoute: typeof EcoHubIndexRoute
}

const EcoHubRouteRouteChildren: EcoHubRouteRouteChildren = {
  EcoHubBlogsRouteRoute: EcoHubBlogsRouteRouteWithChildren,
  EcoHubQuizzesRouteRoute: EcoHubQuizzesRouteRouteWithChildren,
  EcoHubIndexRoute: EcoHubIndexRoute,
}

const EcoHubRouteRouteWithChildren = EcoHubRouteRoute._addFileChildren(
  EcoHubRouteRouteChildren,
)

interface AuthenticatedWriterEcoHubRouteRouteChildren {
  AuthenticatedWriterEcoHubBlogsCreateRoute: typeof AuthenticatedWriterEcoHubBlogsCreateRoute
  AuthenticatedWriterEcoHubBlogsOwnRoute: typeof AuthenticatedWriterEcoHubBlogsOwnRoute
  AuthenticatedWriterEcoHubQuizzesOwnRoute: typeof AuthenticatedWriterEcoHubQuizzesOwnRoute
}

const AuthenticatedWriterEcoHubRouteRouteChildren: AuthenticatedWriterEcoHubRouteRouteChildren =
  {
    AuthenticatedWriterEcoHubBlogsCreateRoute:
      AuthenticatedWriterEcoHubBlogsCreateRoute,
    AuthenticatedWriterEcoHubBlogsOwnRoute:
      AuthenticatedWriterEcoHubBlogsOwnRoute,
    AuthenticatedWriterEcoHubQuizzesOwnRoute:
      AuthenticatedWriterEcoHubQuizzesOwnRoute,
  }

const AuthenticatedWriterEcoHubRouteRouteWithChildren =
  AuthenticatedWriterEcoHubRouteRoute._addFileChildren(
    AuthenticatedWriterEcoHubRouteRouteChildren,
  )

interface AuthenticatedWriterRouteRouteChildren {
  AuthenticatedWriterEcoHubRouteRoute: typeof AuthenticatedWriterEcoHubRouteRouteWithChildren
}

const AuthenticatedWriterRouteRouteChildren: AuthenticatedWriterRouteRouteChildren =
  {
    AuthenticatedWriterEcoHubRouteRoute:
      AuthenticatedWriterEcoHubRouteRouteWithChildren,
  }

const AuthenticatedWriterRouteRouteWithChildren =
  AuthenticatedWriterRouteRoute._addFileChildren(
    AuthenticatedWriterRouteRouteChildren,
  )

interface AuthenticatedReviewsLayoutRouteRouteChildren {
  AuthenticatedReviewsLayoutGivenRoute: typeof AuthenticatedReviewsLayoutGivenRoute
  AuthenticatedReviewsLayoutReceivedRoute: typeof AuthenticatedReviewsLayoutReceivedRoute
}

const AuthenticatedReviewsLayoutRouteRouteChildren: AuthenticatedReviewsLayoutRouteRouteChildren =
  {
    AuthenticatedReviewsLayoutGivenRoute: AuthenticatedReviewsLayoutGivenRoute,
    AuthenticatedReviewsLayoutReceivedRoute:
      AuthenticatedReviewsLayoutReceivedRoute,
  }

const AuthenticatedReviewsLayoutRouteRouteWithChildren =
  AuthenticatedReviewsLayoutRouteRoute._addFileChildren(
    AuthenticatedReviewsLayoutRouteRouteChildren,
  )

interface AuthenticatedReviewsRouteRouteChildren {
  AuthenticatedReviewsLayoutRouteRoute: typeof AuthenticatedReviewsLayoutRouteRouteWithChildren
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
  AuthenticatedReviewsCreateOfferIdRoute: typeof AuthenticatedReviewsCreateOfferIdRoute
}

const AuthenticatedReviewsRouteRouteChildren: AuthenticatedReviewsRouteRouteChildren =
  {
    AuthenticatedReviewsLayoutRouteRoute:
      AuthenticatedReviewsLayoutRouteRouteWithChildren,
    AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
    AuthenticatedReviewsCreateOfferIdRoute:
      AuthenticatedReviewsCreateOfferIdRoute,
  }

const AuthenticatedReviewsRouteRouteWithChildren =
  AuthenticatedReviewsRouteRoute._addFileChildren(
    AuthenticatedReviewsRouteRouteChildren,
  )

interface AuthenticatedAdminCategoriesRouteChildren {
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
}

const AuthenticatedAdminCategoriesRouteChildren: AuthenticatedAdminCategoriesRouteChildren =
  {
    AuthenticatedAdminCategoriesIndexRoute:
      AuthenticatedAdminCategoriesIndexRoute,
  }

const AuthenticatedAdminCategoriesRouteWithChildren =
  AuthenticatedAdminCategoriesRoute._addFileChildren(
    AuthenticatedAdminCategoriesRouteChildren,
  )

interface AuthenticatedAdminUsersUserIdRouteChildren {
  AuthenticatedAdminUsersUserIdItemsRoute: typeof AuthenticatedAdminUsersUserIdItemsRoute
  AuthenticatedAdminUsersUserIdIndexRoute: typeof AuthenticatedAdminUsersUserIdIndexRoute
}

const AuthenticatedAdminUsersUserIdRouteChildren: AuthenticatedAdminUsersUserIdRouteChildren =
  {
    AuthenticatedAdminUsersUserIdItemsRoute:
      AuthenticatedAdminUsersUserIdItemsRoute,
    AuthenticatedAdminUsersUserIdIndexRoute:
      AuthenticatedAdminUsersUserIdIndexRoute,
  }

const AuthenticatedAdminUsersUserIdRouteWithChildren =
  AuthenticatedAdminUsersUserIdRoute._addFileChildren(
    AuthenticatedAdminUsersUserIdRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRouteWithChildren
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute:
      AuthenticatedAdminUsersUserIdRouteWithChildren,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute:
    AuthenticatedAdminCategoriesRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceCreateRoute: typeof AuthenticatedMarketplaceCreateRoute
  AuthenticatedMarketplaceHistoryRoute: typeof AuthenticatedMarketplaceHistoryRoute
  AuthenticatedMarketplaceMyItemsRoute: typeof AuthenticatedMarketplaceMyItemsRoute
  AuthenticatedMarketplaceWishlistRoute: typeof AuthenticatedMarketplaceWishlistRoute
  AuthenticatedMarketplaceItemIdEditRoute: typeof AuthenticatedMarketplaceItemIdEditRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceCreateRoute: AuthenticatedMarketplaceCreateRoute,
    AuthenticatedMarketplaceHistoryRoute: AuthenticatedMarketplaceHistoryRoute,
    AuthenticatedMarketplaceMyItemsRoute: AuthenticatedMarketplaceMyItemsRoute,
    AuthenticatedMarketplaceWishlistRoute:
      AuthenticatedMarketplaceWishlistRoute,
    AuthenticatedMarketplaceItemIdEditRoute:
      AuthenticatedMarketplaceItemIdEditRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedOffersRouteChildren {
  AuthenticatedOffersOwnRoute: typeof AuthenticatedOffersOwnRoute
  AuthenticatedOffersReceivedRoute: typeof AuthenticatedOffersReceivedRoute
  AuthenticatedOffersIndexRoute: typeof AuthenticatedOffersIndexRoute
}

const AuthenticatedOffersRouteChildren: AuthenticatedOffersRouteChildren = {
  AuthenticatedOffersOwnRoute: AuthenticatedOffersOwnRoute,
  AuthenticatedOffersReceivedRoute: AuthenticatedOffersReceivedRoute,
  AuthenticatedOffersIndexRoute: AuthenticatedOffersIndexRoute,
}

const AuthenticatedOffersRouteWithChildren =
  AuthenticatedOffersRoute._addFileChildren(AuthenticatedOffersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedWriterRouteRoute: typeof AuthenticatedWriterRouteRouteWithChildren
  AuthenticatedReviewsRouteRoute: typeof AuthenticatedReviewsRouteRouteWithChildren
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedNotificationsNotificationIdRoute: typeof AuthenticatedNotificationsNotificationIdRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWriterRouteRoute: AuthenticatedWriterRouteRouteWithChildren,
  AuthenticatedReviewsRouteRoute: AuthenticatedReviewsRouteRouteWithChildren,
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedOffersRoute: AuthenticatedOffersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedNotificationsNotificationIdRoute:
    AuthenticatedNotificationsNotificationIdRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
  UnauthenticatedRegisterRoute: typeof UnauthenticatedRegisterRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
  UnauthenticatedRegisterRoute: UnauthenticatedRegisterRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceItemIdRoute: typeof MarketplaceItemIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceItemIdRoute: MarketplaceItemIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ProfileUserIdRouteRouteChildren {
  ProfileUserIdItemsRoute: typeof ProfileUserIdItemsRoute
  ProfileUserIdReviewsRoute: typeof ProfileUserIdReviewsRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
}

const ProfileUserIdRouteRouteChildren: ProfileUserIdRouteRouteChildren = {
  ProfileUserIdItemsRoute: ProfileUserIdItemsRoute,
  ProfileUserIdReviewsRoute: ProfileUserIdReviewsRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
}

const ProfileUserIdRouteRouteWithChildren =
  ProfileUserIdRouteRoute._addFileChildren(ProfileUserIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcoHubRouteRoute: EcoHubRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  ProfileUserIdRouteRoute: ProfileUserIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
