/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as MarketplaceItemIdRouteImport } from './routes/marketplace/$itemId'
import { Route as UnauthenticatedRegisterRouteImport } from './routes/_unauthenticated/register'
import { Route as UnauthenticatedLoginRouteImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedProfileCreateRouteImport } from './routes/_authenticated/profile.create'
import { Route as AuthenticatedMarketplaceWishlistRouteImport } from './routes/_authenticated/marketplace/wishlist'
import { Route as AuthenticatedMarketplaceMyItemsRouteImport } from './routes/_authenticated/marketplace/my-items'
import { Route as AuthenticatedMarketplaceHistoryRouteImport } from './routes/_authenticated/marketplace/history'
import { Route as AuthenticatedMarketplaceCreateRouteImport } from './routes/_authenticated/marketplace/create'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminCategoriesIndexRouteImport } from './routes/_authenticated/admin/categories/index'
import { Route as AuthenticatedMarketplaceItemIdEditRouteImport } from './routes/_authenticated/marketplace/$itemId.edit'
import { Route as AuthenticatedAdminCategoriesCreateIndexRouteImport } from './routes/_authenticated/admin/categories/create/index'
import { Route as AuthenticatedAdminCategoriesEditCategoryIdRouteImport } from './routes/_authenticated/admin/categories/edit/$categoryId'
import { Route as AuthenticatedAdminCategoriesCreateCategoryIdRouteImport } from './routes/_authenticated/admin/categories/create/$categoryId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const MarketplaceItemIdRoute = MarketplaceItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const UnauthenticatedRegisterRoute = UnauthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const UnauthenticatedLoginRoute = UnauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileCreateRoute =
  AuthenticatedProfileCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedMarketplaceWishlistRoute =
  AuthenticatedMarketplaceWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceMyItemsRoute =
  AuthenticatedMarketplaceMyItemsRouteImport.update({
    id: '/my-items',
    path: '/my-items',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceHistoryRoute =
  AuthenticatedMarketplaceHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceCreateRoute =
  AuthenticatedMarketplaceCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesIndexRoute =
  AuthenticatedAdminCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedMarketplaceItemIdEditRoute =
  AuthenticatedMarketplaceItemIdEditRouteImport.update({
    id: '/$itemId/edit',
    path: '/$itemId/edit',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedAdminCategoriesCreateIndexRoute =
  AuthenticatedAdminCategoriesCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesEditCategoryIdRoute =
  AuthenticatedAdminCategoriesEditCategoryIdRouteImport.update({
    id: '/edit/$categoryId',
    path: '/edit/$categoryId',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesCreateCategoryIdRoute =
  AuthenticatedAdminCategoriesCreateCategoryIdRouteImport.update({
    id: '/create/$categoryId',
    path: '/create/$categoryId',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/marketplace/$itemId': typeof MarketplaceItemIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/marketplace/create': typeof AuthenticatedMarketplaceCreateRoute
  '/marketplace/history': typeof AuthenticatedMarketplaceHistoryRoute
  '/marketplace/my-items': typeof AuthenticatedMarketplaceMyItemsRoute
  '/marketplace/wishlist': typeof AuthenticatedMarketplaceWishlistRoute
  '/profile/create': typeof AuthenticatedProfileCreateRoute
  '/marketplace/$itemId/edit': typeof AuthenticatedMarketplaceItemIdEditRoute
  '/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/categories/create/$categoryId': typeof AuthenticatedAdminCategoriesCreateCategoryIdRoute
  '/admin/categories/edit/$categoryId': typeof AuthenticatedAdminCategoriesEditCategoryIdRoute
  '/admin/categories/create/': typeof AuthenticatedAdminCategoriesCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/marketplace': typeof MarketplaceIndexRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/login': typeof UnauthenticatedLoginRoute
  '/register': typeof UnauthenticatedRegisterRoute
  '/marketplace/$itemId': typeof MarketplaceItemIdRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/marketplace/create': typeof AuthenticatedMarketplaceCreateRoute
  '/marketplace/history': typeof AuthenticatedMarketplaceHistoryRoute
  '/marketplace/my-items': typeof AuthenticatedMarketplaceMyItemsRoute
  '/marketplace/wishlist': typeof AuthenticatedMarketplaceWishlistRoute
  '/profile/create': typeof AuthenticatedProfileCreateRoute
  '/marketplace/$itemId/edit': typeof AuthenticatedMarketplaceItemIdEditRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesIndexRoute
  '/admin/categories/create/$categoryId': typeof AuthenticatedAdminCategoriesCreateCategoryIdRoute
  '/admin/categories/edit/$categoryId': typeof AuthenticatedAdminCategoriesEditCategoryIdRoute
  '/admin/categories/create': typeof AuthenticatedAdminCategoriesCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_unauthenticated/register': typeof UnauthenticatedRegisterRoute
  '/marketplace/$itemId': typeof MarketplaceItemIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/marketplace/create': typeof AuthenticatedMarketplaceCreateRoute
  '/_authenticated/marketplace/history': typeof AuthenticatedMarketplaceHistoryRoute
  '/_authenticated/marketplace/my-items': typeof AuthenticatedMarketplaceMyItemsRoute
  '/_authenticated/marketplace/wishlist': typeof AuthenticatedMarketplaceWishlistRoute
  '/_authenticated/profile/create': typeof AuthenticatedProfileCreateRoute
  '/_authenticated/marketplace/$itemId/edit': typeof AuthenticatedMarketplaceItemIdEditRoute
  '/_authenticated/admin/categories/': typeof AuthenticatedAdminCategoriesIndexRoute
  '/_authenticated/admin/categories/create/$categoryId': typeof AuthenticatedAdminCategoriesCreateCategoryIdRoute
  '/_authenticated/admin/categories/edit/$categoryId': typeof AuthenticatedAdminCategoriesEditCategoryIdRoute
  '/_authenticated/admin/categories/create/': typeof AuthenticatedAdminCategoriesCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/unauthorized'
    | '/about'
    | '/admin'
    | '/profile'
    | '/login'
    | '/register'
    | '/marketplace/$itemId'
    | '/marketplace/'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/marketplace/create'
    | '/marketplace/history'
    | '/marketplace/my-items'
    | '/marketplace/wishlist'
    | '/profile/create'
    | '/marketplace/$itemId/edit'
    | '/admin/categories/'
    | '/admin/categories/create/$categoryId'
    | '/admin/categories/edit/$categoryId'
    | '/admin/categories/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/about'
    | '/admin'
    | '/marketplace'
    | '/profile'
    | '/login'
    | '/register'
    | '/marketplace/$itemId'
    | '/admin/dashboard'
    | '/admin/users'
    | '/marketplace/create'
    | '/marketplace/history'
    | '/marketplace/my-items'
    | '/marketplace/wishlist'
    | '/profile/create'
    | '/marketplace/$itemId/edit'
    | '/admin/categories'
    | '/admin/categories/create/$categoryId'
    | '/admin/categories/edit/$categoryId'
    | '/admin/categories/create'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/marketplace'
    | '/unauthorized'
    | '/_authenticated/about'
    | '/_authenticated/admin'
    | '/_authenticated/marketplace'
    | '/_authenticated/profile'
    | '/_unauthenticated/login'
    | '/_unauthenticated/register'
    | '/marketplace/$itemId'
    | '/_authenticated/'
    | '/marketplace/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/users'
    | '/_authenticated/marketplace/create'
    | '/_authenticated/marketplace/history'
    | '/_authenticated/marketplace/my-items'
    | '/_authenticated/marketplace/wishlist'
    | '/_authenticated/profile/create'
    | '/_authenticated/marketplace/$itemId/edit'
    | '/_authenticated/admin/categories/'
    | '/_authenticated/admin/categories/create/$categoryId'
    | '/_authenticated/admin/categories/edit/$categoryId'
    | '/_authenticated/admin/categories/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/marketplace/$itemId': {
      id: '/marketplace/$itemId'
      path: '/$itemId'
      fullPath: '/marketplace/$itemId'
      preLoaderRoute: typeof MarketplaceItemIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/_unauthenticated/register': {
      id: '/_unauthenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthenticatedRegisterRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/create': {
      id: '/_authenticated/profile/create'
      path: '/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof AuthenticatedProfileCreateRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/marketplace/wishlist': {
      id: '/_authenticated/marketplace/wishlist'
      path: '/wishlist'
      fullPath: '/marketplace/wishlist'
      preLoaderRoute: typeof AuthenticatedMarketplaceWishlistRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/my-items': {
      id: '/_authenticated/marketplace/my-items'
      path: '/my-items'
      fullPath: '/marketplace/my-items'
      preLoaderRoute: typeof AuthenticatedMarketplaceMyItemsRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/history': {
      id: '/_authenticated/marketplace/history'
      path: '/history'
      fullPath: '/marketplace/history'
      preLoaderRoute: typeof AuthenticatedMarketplaceHistoryRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/create': {
      id: '/_authenticated/marketplace/create'
      path: '/create'
      fullPath: '/marketplace/create'
      preLoaderRoute: typeof AuthenticatedMarketplaceCreateRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories/': {
      id: '/_authenticated/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/marketplace/$itemId/edit': {
      id: '/_authenticated/marketplace/$itemId/edit'
      path: '/$itemId/edit'
      fullPath: '/marketplace/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedMarketplaceItemIdEditRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/admin/categories/create/': {
      id: '/_authenticated/admin/categories/create/'
      path: '/create'
      fullPath: '/admin/categories/create/'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesCreateIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/edit/$categoryId': {
      id: '/_authenticated/admin/categories/edit/$categoryId'
      path: '/edit/$categoryId'
      fullPath: '/admin/categories/edit/$categoryId'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesEditCategoryIdRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/create/$categoryId': {
      id: '/_authenticated/admin/categories/create/$categoryId'
      path: '/create/$categoryId'
      fullPath: '/admin/categories/create/$categoryId'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesCreateCategoryIdRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
  }
}

interface AuthenticatedAdminCategoriesRouteChildren {
  AuthenticatedAdminCategoriesIndexRoute: typeof AuthenticatedAdminCategoriesIndexRoute
  AuthenticatedAdminCategoriesCreateCategoryIdRoute: typeof AuthenticatedAdminCategoriesCreateCategoryIdRoute
  AuthenticatedAdminCategoriesEditCategoryIdRoute: typeof AuthenticatedAdminCategoriesEditCategoryIdRoute
  AuthenticatedAdminCategoriesCreateIndexRoute: typeof AuthenticatedAdminCategoriesCreateIndexRoute
}

const AuthenticatedAdminCategoriesRouteChildren: AuthenticatedAdminCategoriesRouteChildren =
  {
    AuthenticatedAdminCategoriesIndexRoute:
      AuthenticatedAdminCategoriesIndexRoute,
    AuthenticatedAdminCategoriesCreateCategoryIdRoute:
      AuthenticatedAdminCategoriesCreateCategoryIdRoute,
    AuthenticatedAdminCategoriesEditCategoryIdRoute:
      AuthenticatedAdminCategoriesEditCategoryIdRoute,
    AuthenticatedAdminCategoriesCreateIndexRoute:
      AuthenticatedAdminCategoriesCreateIndexRoute,
  }

const AuthenticatedAdminCategoriesRouteWithChildren =
  AuthenticatedAdminCategoriesRoute._addFileChildren(
    AuthenticatedAdminCategoriesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute:
    AuthenticatedAdminCategoriesRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceCreateRoute: typeof AuthenticatedMarketplaceCreateRoute
  AuthenticatedMarketplaceHistoryRoute: typeof AuthenticatedMarketplaceHistoryRoute
  AuthenticatedMarketplaceMyItemsRoute: typeof AuthenticatedMarketplaceMyItemsRoute
  AuthenticatedMarketplaceWishlistRoute: typeof AuthenticatedMarketplaceWishlistRoute
  AuthenticatedMarketplaceItemIdEditRoute: typeof AuthenticatedMarketplaceItemIdEditRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceCreateRoute: AuthenticatedMarketplaceCreateRoute,
    AuthenticatedMarketplaceHistoryRoute: AuthenticatedMarketplaceHistoryRoute,
    AuthenticatedMarketplaceMyItemsRoute: AuthenticatedMarketplaceMyItemsRoute,
    AuthenticatedMarketplaceWishlistRoute:
      AuthenticatedMarketplaceWishlistRoute,
    AuthenticatedMarketplaceItemIdEditRoute:
      AuthenticatedMarketplaceItemIdEditRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileCreateRoute: typeof AuthenticatedProfileCreateRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileCreateRoute: AuthenticatedProfileCreateRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
  UnauthenticatedRegisterRoute: typeof UnauthenticatedRegisterRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
  UnauthenticatedRegisterRoute: UnauthenticatedRegisterRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceItemIdRoute: typeof MarketplaceItemIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceItemIdRoute: MarketplaceItemIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
