name: Frontend to vps

on:
  push:
    branches: ["main"]

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Login to Github Container Registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build . -t ghcr.io/${{secrets.DOCKER_USERNAME }}/zero-waste-frontend:latest

      - name: Push Image
        run: docker push ghcr.io/${{secrets.DOCKER_USERNAME }}/zero-waste-frontend:latest

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{secrets.VPS_USER}}@${{secrets.VPS_HOST}} << 'EOF'
            cd ${{secrets.PROJECT_DIR}}
            docker compose pull frontend
            docker compose up -d
          EOF
